version: '3'

services:
  nginx_chat:
    container_name: chat.nginx
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - .:/var/www/project
      - ./docker/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites-enabled:/etc/nginx/sites-enabled
      - ./docker/nginx/ssl:/etc/nginx/ssl
    ports:
      - "80:80"
      - "443:443"

  nodejs:
    container_name: chat.node
    command: "npm run start-dev"
    image: node:10.17.0-jessie
    working_dir: /var/www/project
    ports:
      - "3000:3000"
    volumes:
      - .:/var/www/project